### ISSUE TITLE
JSON integer 4665092905 is too large or small for an Int32. Path 'Data[0].CampaignID', line 1, position 133.

### ISSUE THREAD

**Issue by vtecpest** [AshleyMedway/MailJet.NET#1]
Hi,

I think this means the compaignID property needs changing to a long within the mailjet.net codebase?

An unhandled exception of type 'Newtonsoft.Json.JsonReaderException' occurred in Newtonsoft.Json.dll

Additional information: JSON integer 4665092905 is too large or small for an Int32. Path 'Data[0].CampaignID', line 1, position 133.

**Comment by AshleyMedway** [comment]
Thanks @vtecpest I will take a look at this tonight
