### ISSUE TITLE
MailJet.NET failing with RestSharp 105.2.3.0

### ISSUE THREAD

**Issue by beyondwebdevelopment** [AshleyMedway/MailJet.NET#10]
Just letting you know, HttpBasicAuthenticator has been moved around to a different namespace, so MailJet.NET fails when using RestSharp 105.2.3.0

Exception thrown: 'System.TypeLoadException' in MailJetClient.dll ("Could not load type 'RestSharp.HttpBasicAuthenticator' from assembly 'RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null'.")

PS - good job on this project, saved me a bunch of time :)

**Comment by AshleyMedway** [comment]
v1.4.2 has been updated to use the latest version of RestSharp let me know if this fixes your issue and I will close the issue :)
