### ISSUE TITLE
Statistics API

### ISSUE THREAD

**Issue by cedrox** [AshleyMedway/MailJet.NET#11]
Hello,
First, Thanks for your work !
Have you plan to integrate statistics api ?
http://dev.mailjet.com/email-api/v3/aggregategraphstatistics/

Thanks

**Comment by AshleyMedway** [comment]
Yeah this looks fairly straight forward. I've got some stuff to finish up around the templates but I will add this next  :+1:

**Comment by AshleyMedway** [comment]
`/aggregategraphstatistics/` is in v1.5.0 more statistics api will be in future versions :)

**Comment by cedrox** [comment]
That's awesome !
Big Thank !
