### ISSUE TITLE
Statistics API aggregate parameter

### ISSUE THREAD

**Issue by cedrox** [AshleyMedway/MailJet.NET#13]
Hello, 
It seem to be impossible to use statistic api without method about campaign management. Particularly method on campaignaggregate (https://dev.mailjet.com/email-api/v3/campaignaggregate/). 
From my actual perspective, you have to create a campaignaggregate, include some campaign inside and request statistics with CampaignAggregateID (https://dev.mailjet.com/email-api/v3/aggregategraphstatistics/). When I use method GetAggregateGraphStatistics who call method aggregategraphstatistics without any parameter, I have no result. When I pass CampaingID, I have no result neither.

**Comment by cedrox** [comment]
from the Getting started :

The /messagestatistics resource aggregates statistics on your selected filter. It is showing a count of each event attached to the messages you filtered on.

By default if no filter is defined, this resource will aggregate todays messages statistics. You can use the filters FromTS and ToTS (Unix timestamp) to specify the period of extraction.

Visit the /messagestatistics resource reference for a full list of available filters.

http://dev.mailjet.com/email-api/v3/messagestatistics/

**Comment by cedrox** [comment]
To get detailled statistics day by day, you have to request Mailjet statistic API at Campaign level and use complex mechanism of campaign aggregate entity. If you want global statistic, message api is enough...

**Comment by cedrox** [comment]
Maybe I can participate to development ?

**Comment by AshleyMedway** [comment]
Yeah I've not really had to use the statistics side very much.

Please participate in development :) 

Just fork the project then create a pull request when you are ready.

Its fairly straight forward all the functional methods are in the MailJetClient.cs and there is a Statistics Unit Test file if you want to write some unit test. Just be careful you do not commit your API key anywhere :+1:

**Comment by cedrox** [comment]
Hello Ashley,
Thanks to integrate me to your dev effort. 
I began to dev and I see that your code is perfect for transactionnal email but it's not so well for campaign email. As you use Mail from System.Net.Mail, you have to omit some important notion... I think particularly to campaign ID. 
Let me explain the scenario : I want to send same mail to 20 peoples from the same sender. This mail is templated into my app. I don't want that the mail get the 20 recipients into the "to" field and I want to get an aggregate statistical view. If I send 20 mail via send/message, I cannot attache a CustomID or a Campaign ID. Then I cannot get this stat view easily.
My Solution would be to use a dedicated datamodel (separate from .NET MailMessage), taken from the mailjet datamodel to access property Mj-campaign
http://dev.mailjet.com/guides/#send-api-json-properties
What do you think ?
PS : I don't wan't to use mailjet Template feature.

**Comment by AshleyMedway** [comment]
I understand your requirement. Version 1 is based of the .NET MailMessage to provide a simple transition for those who wish to send transaction based email. Version 2 will be a PCL version and .NET MailMessage is removed.

I think the easiest way to add the `MJ-Campaign` property will be to edit the following method.

```
public Response<DataItem> SendMessage(MailMessage Message)
```

to

```
public Response<DataItem> SendMessage(MailMessage Message, string CampaignId = null)
```

Thoughts?

**Comment by cedrox** [comment]
I did a commit  in a Statistic branch. Please see if it's ok for you. 
The idea is to use a full feature object with all the properties.
Maybe it will be good to do all the validation in the constructor and send a seriablized body ? Doing all the validation in the client seem to be not so good...
Maybe it will be good to to use a constructor with MailMessage parameter ?
public Response<DataItem> SendMessage(MailMessage Message)
will be
public Response<DataItem> SendMessage(MailjetSendMail Message)
with implicit convertion like 
var maijetMessage = new MailjetSendMail(mailMessage);

NB : Don't worry, I will clean the code after discussion ;)

Let me know.

**Comment by AshleyMedway** [comment]
I cannot see your commit, is the branch private?

**Comment by cedrox** [comment]
Sorry Ashley, I was thinking that I had permission to commit the statistic branch but I cannot actually...
Opening repositories:
C:\Users\Cedric\Source\Repos\MailJet.NET
Error encountered while publishing branch to the remote repository: Response status code does not indicate success: 403 (Forbidden).

**Comment by cedrox** [comment]
Hello Ashley, 
Actually I wanted to create a branch called statistic and sync my commit in order for you to review what I did. Can you setup permission to do so ?

**Comment by AshleyMedway** [comment]
On github you need to create your own fork of the project. Here you can commit to your own copy. When you are ready you can then create a pull request to merge your work back into the master branch. There is a nice explanation of the workflow here: https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by cedrox** [comment]
Hello, I think that what I did.
I create the fork statistic and then I commit remotely to this fork... I need authorization to create and commit to my branch...
If you accept changes, we could merge after ?
Thanks

**Comment by AshleyMedway** [comment]
You need to create your own fork, you cannot commit directly to the repository.

<img width="151" alt="untitled" src="https://cloud.githubusercontent.com/assets/1255596/17114047/313ba04a-52a5-11e6-8525-efa411b659bb.png">

**Comment by cedrox** [comment]
Thanks for git support Ashley. I am quite noobs on this for the moment. 
Please check Statistics branch and let me know.

Thanks

**Comment by cedrox** [comment]
I had an interesting call with mailjet support today.
It's better option to use /graphstatistics to get data than /aggregategraphstatistics as it's more easy to use. 
I have to implement methods on this. 
I will commit quickly.
Thanks

**Comment by cedrox** [comment]
Pull request pending.
Let me know

**Comment by cedrox** [comment]
Hello,
Any comment on this ?

**Comment by AshleyMedway** [comment]
closing as part of #15
