### ISSUE TITLE
GetContactData(id) is returning a null object

### ISSUE THREAD

**Issue by dapug** [AshleyMedway/MailJet.NET#16]
If you run client.GetContactData(<id>), you get back an empty object, email and other properties are null, CreatedAt date is minvalue (sure shouldn't be).  I tried this with a known-good contact, correct ID, has email and other properties populated in MailJet.

**Comment by dapug** [comment]
I fixed this. See Pull Request if you want to apply this for everyone.

**Comment by AshleyMedway** [comment]
Thanks David, I was away on holiday, will pull this in now :+1:
