### ISSUE TITLE
Message attachement

### ISSUE THREAD

**Issue by AndreJUILLARD** [AshleyMedway/MailJet.NET#24]
Why attacjement are only sent using SMTP and not with API ..?

With the same message,
using SMTP
`
System.Net.Mail.SmtpClient serv = new System.Net.Mail.SmtpClient("in-v3.mailjet.com");
serv.Credentials = new System.Net.NetworkCredential("xxx", "xxx");
serv.Send(mess);
`
The message has attachements

And using API
`
MailJet.Client.MailJetClient client = new MailJet.Client.MailJetClient("xxx", "xxx");
client.SendMessage(mess)
`
The email has no attachements ..?

**Comment by AshleyMedway** [comment]
I'll take a look, it should handle attachments 👍

**Comment by isimongardner** [comment]
Just to give a heads up, looks like attachments have stopped working in production here. API maybe deprecated. Talking to MailJet.

**Comment by AndreJUILLARD** [comment]
Ok ... wait & see
