### ISSUE TITLE
License restrictions?

### ISSUE THREAD

**Issue by appelgriebsch** [AshleyMedway/MailJet.NET#27]
Hey, we would like to use the library in a commercial application and are now looking into the licensing aspect of it. Actually you make the source code available for free on GitHub, but you didn't specify under which license the code can be used? Is it Apache License, MIT, GPL, ... ?

Could you pls. clarify this.

Thx.

**Comment by AshleyMedway** [comment]
What works best? MIT?

**Comment by AshleyMedway** [comment]
https://github.com/AshleyMedway/MailJet.NET/blob/master/LICENSE
