### ISSUE TITLE
Adding/editing a custom contact parameter does nothing

### ISSUE THREAD

**Issue by luminalpark** [AshleyMedway/MailJet.NET#4]
When I create a new contact or update an existing one, custom parameters (already defined in Mailjet) seem to be ignored.

`var props = new Dictionary<string,string>();`
     `props.Add("x", "9");`
`var contact = new MailJet.Client.Request.Contact
      {
        Email = email,
        Name = "testName",
        Action = CreateContactAction.addforce,
Properties = props
      };`
     `Response<ContactData> resp= client.CreateContactForList(listId, contact);`

**Comment by AshleyMedway** [comment]
Yeah agreed, looking into this now :+1:

**Comment by AshleyMedway** [comment]
Everything seems to POST to MailJet correctly. I have emailed MailJet and am awaiting a response.

**Comment by luminalpark** [comment]
I've been in contact with Mailjet support, maybe the reason of this problem is related to the verb, it should be **PUT**, not **POST**.
ex:

https://api.mailjet.com/v3/REST/contactdata/email-id

```
{Data:
 [
   {"Name":"prop1","Value":0,
     "Name":"prop2","Value":9
   }
 ]
}
```

**Comment by AshleyMedway** [comment]
I'll try this now, but **PUT** is normally used to update an existing record not create a new one. At the moment the package only creates new records via: `REST/contactslist/{id}/managecontact`

**Comment by AshleyMedway** [comment]
I think I have narrowed this down, it is due to the way in which they expect to see the parameter **TKEYVALUELIST** a data type which is not documented. The json object needs to be sent as 

```
data: [{"Name": "prop", "Value": "test"}, etc.]
```

I am writing a custom converter to convert Dictionary to this format
