### ISSUE TITLE
Message sent twice

### ISSUE THREAD

**Issue by patuzov** [AshleyMedway/MailJet.NET#8]
Hi!
First of all, thanks for the library!

I am trying to send a message using the sample code:

```
MailJetClient client = new MailJetClient("{PublicKey}", "{PrivateKey}");
client.SendMessage(new System.Net.Mail.MailMessage("from@email.com", "to@email.com", "subject", "email body"));
```

For some reason, it makes 2 requests on mailjet and I receive the email twice in my inbox:
<img width="600" alt="screen shot 2016-04-19 at 18 37 12" src="https://cloud.githubusercontent.com/assets/8795464/14647489/4f0eb5b4-065e-11e6-87fb-277ce5f1896a.png">

What am I missing? Did anyone have such problems?

Thanks!

**Comment by patuzov** [comment]
Take a look at the end of the SendMessage method:

```
var response = WebClient.Execute(request);
if (response.StatusCode != HttpStatusCode.OK)
    throw response.ErrorException ?? new Exception(response.StatusDescription);
return ExecuteRequest<DataItem>(request);
```

The request is being sent twice indeed.

**Comment by AshleyMedway** [comment]
Thanks, I'll check this now 👍

**Comment by AshleyMedway** [comment]
fixed - I will push a new release to NuGet now
